### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by asianking** [alex-free/gshax-tool#1]
Your win64 download link is down.

**Comment by alex-free** [comment]
Working fine on both website and GitHub page https://github.com/alex-free/gshax-tool/releases/download/v2.0.1/gshax-tool-v2.0.1-windows_x86_64.zip

**Comment by alex-free** [comment]
Only works on my phone (safari?) Not working on firefox, use the release link for now: https://github.com/alex-free/gshax-tool/releases/tag/v2.0.1

**Comment by alex-free** [comment]
Fixed thanks!
